@startuml DatabaseSchema

Entity Office {
    * office_id : PK INT
    ---
    * max_capacity : INT
    * street_address : VARCHAR(60)
    * state : VARCHAR(2)
    * phone : VARCHAR(20)
}

Entity Employee {
    * employee_id : PK INT
    * first_name : VARCHAR(30)
    * last_name : VARCHAR(30)
    * job_title : VARCHAR(60)
    * employment_status : ENUM('Full Time', 'Part Time', 'Internship', 'Inactive', 'On Leave')
    * email : VARCHAR(45)
    * office_id : FK INT
}

Office "1" -- "0..*" Employee : Contains

@enduml
